TargetBraNCH='develop-test'
password=qwertyasjasdadasdsda
AWS_ACCESS_KEY="ASDUHAEUR73923MSA9"
git checkout $TargetBraNCH
AWS_SECRET_ACCESS_KEY="qwerty"
GH_Token=ghp_KLMKJDsdfsdiewneflfc
AWS_Password=asdajndoefnldsanasCASLDMCALASDNLASND
password=abcrfddhsybfsdkjnrrendrfj
